"""Core Capability Broker public surface.

The broker is deliberately a port-only orchestration boundary.  It owns no
Core database connection and it never calls Job, Event, Candidate, or
Publication implementations directly.  Production composition supplies the
durable ports; the in-memory ports exported here are deterministic test
adapters only.
"""

from .service import (
    AttemptContextPort,
    BrokerAggregation,
    BrokerBinding,
    BrokerCancelResult,
    BrokerChildFactoryPort,
    BrokerChildRecord,
    BrokerChildRecordPort,
    BrokerChildRecordStore,
    BrokerChildSnapshotPort,
    BrokerCoreAssetPort,
    BrokerDescriptorPort,
    BrokerExecutionPort,
    BrokerInvocationEnvelope,
    BrokerInvokeResult,
    BrokerLedgerEntry,
    BrokerOperationLedgerPort,
    BrokerOperationReservation,
    BrokerPollProjection,
    BrokerReceiptPropagation,
    BrokerReceiptPort,
    CapabilityBinding,
    CapabilityDescriptor,
    CapabilityBroker,
    CallerAttemptContext,
    ChildCreationRequest,
    ChildCreationResult,
    InMemoryAttemptContextPort,
    InMemoryBrokerChildRecordStore,
    InMemoryBrokerOperationLedger,
    InvocationEnvelope,
    InvokeResult,
    PollResult,
    aggregate_child_outcomes,
    build_receipt_propagation,
    derive_child_cancel_operation_key,
    propagate_receipts,
    verify_child_snapshot_binding,
)

__all__ = [
    "AttemptContextPort",
    "BrokerAggregation",
    "BrokerBinding",
    "BrokerCancelResult",
    "BrokerChildFactoryPort",
    "BrokerChildRecord",
    "BrokerChildRecordPort",
    "BrokerChildRecordStore",
    "BrokerChildSnapshotPort",
    "BrokerCoreAssetPort",
    "BrokerDescriptorPort",
    "BrokerExecutionPort",
    "BrokerInvocationEnvelope",
    "BrokerInvokeResult",
    "BrokerLedgerEntry",
    "BrokerOperationLedgerPort",
    "BrokerOperationReservation",
    "BrokerPollProjection",
    "BrokerReceiptPort",
    "BrokerReceiptPropagation",
    "CapabilityBinding",
    "CapabilityDescriptor",
    "CapabilityBroker",
    "CallerAttemptContext",
    "ChildCreationRequest",
    "ChildCreationResult",
    "InMemoryAttemptContextPort",
    "InMemoryBrokerChildRecordStore",
    "InMemoryBrokerOperationLedger",
    "InvocationEnvelope",
    "InvokeResult",
    "PollResult",
    "aggregate_child_outcomes",
    "build_receipt_propagation",
    "derive_child_cancel_operation_key",
    "propagate_receipts",
    "verify_child_snapshot_binding",
]
