import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const home = readFileSync(new URL('../../../frontend/src/views/Home.vue', import.meta.url), 'utf8')
const workbench = readFileSync(new URL('../../../frontend/src/views/Workbench.vue', import.meta.url), 'utf8')
const chapterList = readFileSync(new URL('../../../frontend/src/core/flows/CoreChapterList.vue', import.meta.url), 'utf8')
const runtime = readFileSync(new URL('../../../frontend/src/core/flows/runtime.ts', import.meta.url), 'utf8')

test('Home is wired to Core flows without a wizard or legacy project authority', () => {
  assert.match(home, /requireCoreFlowRuntime\(\)\.listProjects\(\)/)
  assert.match(home, /requireCoreFlowRuntime\(\)\.createProjectWithBrief/)
  assert.match(home, /requireCoreFlowRuntime\(\)\.deleteProject/)
  assert.doesNotMatch(home, /novelApi|NovelSetupGuide|isWizardCompleted|setupWizard|StatsSidebar/)
  assert.doesNotMatch(home, /requireCoreFlowRuntime\(\)\.createProject\(newBook\.value\.title\)/)
  assert.match(home, /Project Planner package\/lifecycle 尚未可用/)
  assert.match(home, /premise: newBook\.value\.premise/)
  assert.match(home, /genre: newBook\.value\.genre/)
  assert.match(home, /customChapters: newBook\.value\.chapters/)
  assert.match(home, /customWordsPerChapter: newBook\.value\.words/)
  assert.match(home, /:disabled="creating"/)
  assert.match(home, /projectListGeneration\.begin\('project-list'\)/)
  assert.match(home, /if \(!projectListGeneration\.isCurrent\(requestGeneration\)\) return false/)
  assert.match(home, /const succeededIds = new Set<string>\(\)/)
  assert.match(home, /reconcilePartialDeleteSelection\(selectedBooks\.value, succeededIds, localAuthorityIds\)/)
  assert.match(home, /await fetchBooks\(\)/)
})

test('Workbench keeps the three-pane split while using document identity for open/edit/save', () => {
  assert.equal((workbench.match(/<n-split/g) ?? []).length, 2)
  assert.match(workbench, /<CoreChapterList/)
  assert.match(workbench, /<CoreChapterEditor/)
  assert.match(workbench, /@create="handleChapterCreate"/)
  assert.match(workbench, /:busy="pageLoading \|\| chapterLoading \|\| chapterSaving \|\| chapterCreating"/)
  assert.match(workbench, /const title = `第 \$\{chapters\.value\.length \+ 1\} 章`/)
  assert.match(workbench, /createCoreChapterRecovery\(\)/)
  assert.match(workbench, /chapterCreateRecovery\.run\(workspaceId, title/)
  assert.match(workbench, /requireCoreFlowRuntime\(\)\.createChapter\(targetWorkspaceId, targetTitle\)/)
  assert.match(workbench, /const title = [^\n]+\n  chapterDeskReload\.cancel\(\)\n  chapterCreating\.value = true/)
  assert.match(workbench, /const created = await requireCoreFlowRuntime\(\)\.createChapter\(targetWorkspaceId, targetTitle\)\n        chapterDeskReload\.cancel\(\)\n        return created/)
  assert.match(workbench, /chapterCreateRecovery\.hasCommittedChapter\(workspaceId\)/)
  assert.equal((workbench.match(/chapterCreateRecovery\.canRunOrdinaryReload\(token\.scope\)/g) ?? []).length, 2)
  assert.match(workbench, /parseChapterQuery\(route\.query\.chapter\) !== targetDocumentId/)
  assert.match(workbench, /let createSequence = 0/)
  assert.match(workbench, /currentDocumentId/)
  assert.match(workbench, /route\.query\.chapter !== documentId/)
  assert.match(workbench, /requireCoreFlowRuntime\(\)\.saveChapter/)
  assert.match(workbench, /const workspaceGeneration = new ScopedRequestGeneration\(\)/)
  assert.match(workbench, /const token = workspaceGeneration\.begin\(workspaceId\)/)
  assert.match(workbench, /chapters\.value = \[\]/)
  assert.match(workbench, /workspaceDraftKey\(workspaceId, documentId\)/)
  assert.match(workbench, /requestSequence !== saveSequence/)
  assert.match(workbench, /requestSequence !== deskSequence/)
  assert.doesNotMatch(workbench, /useWorkbench|novelApi|chapterApi|<WorkArea|<ChapterList|<StatsTopBar|<SettingsPanel/)
})

test('CoreChapterList exposes a clear creation action without introducing a wizard', () => {
  assert.match(chapterList, />新建章节<\/n-button>/)
  assert.match(chapterList, /\$emit\('create'\)/)
  assert.match(chapterList, /create: \[\]/)
  assert.doesNotMatch(chapterList, /wizard|Guide/i)
})

test('runtime composition has no default fake, legacy fallback, or implicit HTTP mount', () => {
  assert.match(runtime, /let runtime: CoreFlows \| null = null/)
  assert.match(runtime, /P0-owned runtime composition/)
  assert.doesNotMatch(runtime, /createCoreHttpFlowGateway|novelApi|chapterApi/)
})
